# Generated by Django 4.0.4 on 2022-05-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userDetails',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=50)),
                ('about', models.CharField(default='', max_length=250)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('linkedin', models.URLField(max_length=300)),
                ('github', models.URLField(max_length=300)),
                ('address', models.CharField(max_length=50)),
                ('master_year_from', models.IntegerField()),
                ('master_year_to', models.IntegerField()),
                ('master_degree', models.CharField(max_length=50)),
                ('university_name', models.CharField(max_length=100)),
                ('school_year_from', models.IntegerField()),
                ('school_year_to', models.IntegerField()),
                ('school_degree', models.CharField(max_length=50)),
                ('school_name', models.CharField(max_length=100)),
                ('lang1', models.CharField(max_length=30)),
                ('lang2', models.CharField(max_length=30)),
                ('hobby1', models.CharField(max_length=100)),
                ('hobby2', models.CharField(max_length=100)),
                ('hobby3', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('company_role', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('company_year_from', models.IntegerField()),
                ('company_year_to', models.IntegerField()),
                ('role', models.CharField(max_length=500)),
                ('project_title', models.CharField(max_length=500)),
                ('project_link', models.URLField(max_length=300)),
                ('project_tagline', models.CharField(max_length=500)),
                ('skill1', models.CharField(max_length=100)),
                ('skill2', models.CharField(max_length=100)),
                ('skill3', models.CharField(max_length=100)),
                ('skill4', models.CharField(max_length=100)),
                ('skill5', models.CharField(max_length=100)),
                ('achievement1', models.CharField(max_length=300)),
                ('achievement2', models.CharField(max_length=300)),
            ],
        ),
    ]
