# Generated by Django 4.0.4 on 2022-05-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='uid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
