# Generated by Django 4.0.4 on 2022-05-22 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_userdetails_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='achievement2',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='hobby2',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='hobby3',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='lang2',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='skill2',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='skill3',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='skill4',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='skill5',
        ),
    ]
